### ISSUE TITLE
大写锁定键无效

### ISSUE THREAD

**Issue by Endermanpoi** [darkhandz/XPS15-9550-Catalina#1]
大写锁定键按下没有任何作用，而且指示灯也不会亮
用wmchris的EFI只有按住时会亮，功能倒是正常，换你的EFI就彻底失效了
而且似乎变频不是很完美

**Comment by darkhandz** [comment]
按键的问题是我个人定制忘记删除了 240206543d6f3749ccbc658124ca790c387e7949
变频问题得另外看看，你也可以用其他人的CPUFriendDataProvider.kext替换试试

**Comment by Endermanpoi** [comment]
感谢大佬，研究了一晚终于搞定了变频问题，分享给大佬看看。  
更换CPUFriendDataProvider似乎没有效果，闲置状态CPU都是2.0G左右，我加入了wmchris的[SSDT-TPDX](https://github.com/wmchris/DellXPS15-9550-OSX/blob/10.15/10.15/CLOVER/ACPI/patched/SSDT-TPDX.aml)后可以得到0.8G的闲置频率，但是睡眠唤醒VoodooI2C会崩溃，参考[issue](https://github.com/alexandred/VoodooI2C/issues/231)回退到2.2后正常。

**Comment by darkhandz** [comment]
方案有效，我屏蔽I2C0并用回2.2
![image](https://user-images.githubusercontent.com/2143333/72090089-47979600-3348-11ea-9c28-e30e71e96249.png)
