### ISSUE TITLE
睡眠唤醒后外接显示器无法唤醒

### ISSUE THREAD

**Issue by Endermanpoi** [darkhandz/XPS15-9550-Catalina#5]
10.15.4下，HDMI外接显示器，睡眠后唤醒机子，外接的显示器不会被唤醒，需要重新拔插。（之前版本可以）
问题来自[issue](https://github.com/Endermanpoi/XPS9550-macOS/issues/5)，我自己也复现了，但是解决不了。使用的CLOVER是5108版本。

**Comment by darkhandz** [comment]
我自己使用没有遇到这个问题哦，我更新了也有4天了，只在晚上开几个小时，目前没有问题，最新配置也就只更新了几个驱动和Clover，已上传了

**Comment by duguhu007** [comment]
同样遇到只要睡眠或者屏幕熄灭进入省电模式后外接显示器就点不亮了,需要重新拔插HDMI才可以

**Comment by china-lee** [comment]
可以试试在启动参数里加上 igfxonln=1，我目前clover 5117，WhateverGreen 1.3.9，lilu 1.4.4。测试有效，可以唤醒外接的显示器。

**Comment by Endermanpoi** [comment]
> 可以试试把 WhateverGreen 更新到 1.3.8 及以上，然后在启动参数里加上 igfxonln=1，我目前clover 5117，WhateverGreen 1.3.9，lilu 1.4.4。测试有效，可以唤醒外接的显示器。

解决了，感谢！！！
